export const provinces = [
  { id: 'AC', name: 'Aceh' },
  { id: 'SU', name: 'Sumatera Utara' },
  { id: 'SB', name: 'Sumatera Barat' },
  { id: 'RI', name: 'Riau' },
  { id: 'JA', name: 'Jambi' },
  { id: 'SS', name: 'Sumatera Selatan' },
  { id: 'BE', name: 'Bengkulu' },
  { id: 'LA', name: 'Lampung' },
  { id: 'BB', name: 'Kepulauan Bangka Belitung' },
  { id: 'KR', name: 'Kepulauan Riau' },
  { id: 'JK', name: 'DKI Jakarta' },
  { id: 'JB', name: 'Jawa Barat' },
  { id: 'JT', name: 'Jawa Tengah' },
  { id: 'JI', name: 'Jawa Timur' },
  { id: 'YO', name: 'DI Yogyakarta' },
  { id: 'BT', name: 'Banten' },
  { id: 'BA', name: 'Bali' },
  { id: 'NB', name: 'Nusa Tenggara Barat' },
  { id: 'NT', name: 'Nusa Tenggara Timur' },
  { id: 'KB', name: 'Kalimantan Barat' },
  { id: 'KT', name: 'Kalimantan Tengah' },
  { id: 'KS', name: 'Kalimantan Selatan' },
  { id: 'KI', name: 'Kalimantan Timur' },
  { id: 'KU', name: 'Kalimantan Utara' },
  { id: 'SA', name: 'Sulawesi Utara' },
  { id: 'ST', name: 'Sulawesi Tengah' },
  { id: 'SN', name: 'Sulawesi Selatan' },
  { id: 'SG', name: 'Sulawesi Tenggara' },
  { id: 'GO', name: 'Gorontalo' },
  { id: 'SR', name: 'Sulawesi Barat' },
  { id: 'MA', name: 'Maluku' },
  { id: 'MU', name: 'Maluku Utara' },
  { id: 'PA', name: 'Papua' },
  { id: 'PB', name: 'Papua Barat' },
  { id: 'PD', name: 'Papua Barat Daya' },
  { id: 'PS', name: 'Papua Selatan' },
  { id: 'PT', name: 'Papua Tengah' },
  { id: 'PP', name: 'Papua Pegunungan' }
]

export const cities: Record<string, string[]> = {
  AC: ['Banda Aceh', 'Sabang', 'Lhokseumawe', 'Langsa', 'Subulussalam'],
  SU: ['Medan', 'Pematang Siantar', 'Sibolga', 'Tanjung Balai', 'Binjai', 'Tebing Tinggi', 'Padang Sidempuan', 'Gunungsitoli'],
  SB: ['Padang', 'Solok', 'Sawahlunto', 'Padang Panjang', 'Bukittinggi', 'Payakumbuh', 'Pariaman'],
  RI: ['Pekanbaru', 'Dumai'],
  JA: ['Jambi', 'Sungai Penuh'],
  SS: ['Palembang', 'Prabumulih', 'Pagar Alam', 'Lubuklinggau'],
  BE: ['Bengkulu'],
  LA: ['Bandar Lampung', 'Metro'],
  BB: ['Pangkal Pinang'],
  KR: ['Tanjung Pinang', 'Batam'],
  JK: ['Jakarta Pusat', 'Jakarta Utara', 'Jakarta Barat', 'Jakarta Selatan', 'Jakarta Timur', 'Kepulauan Seribu'],
  JB: ['Bandung', 'Bogor', 'Sukabumi', 'Tasikmalaya', 'Cimahi', 'Depok', 'Bekasi', 'Banjar', 'Cirebon'],
  JT: ['Semarang', 'Surakarta (Solo)', 'Salatiga', 'Magelang', 'Pekalongan', 'Tegal'],
  JI: ['Surabaya', 'Malang', 'Madiun', 'Kediri', 'Mojokerto', 'Blitar', 'Pasuruan', 'Probolinggo', 'Batu'],
  YO: ['Yogyakarta', 'Sleman', 'Bantul', 'Kulon Progo', 'Gunung Kidul'],
  BT: ['Serang', 'Cilegon', 'Tangerang', 'Tangerang Selatan'],
  BA: ['Denpasar', 'Badung', 'Gianyar', 'Tabanan', 'Bangli', 'Klungkung', 'Karangasem', 'Buleleng', 'Jembrana'],
  NB: ['Mataram', 'Bima'],
  NT: ['Kupang'],
  KB: ['Pontianak', 'Singkawang'],
  KT: ['Palangka Raya'],
  KS: ['Banjarmasin', 'Banjarbaru'],
  KI: ['Samarinda', 'Balikpapan', 'Bontang'],
  KU: ['Tarakan'],
  SA: ['Manado', 'Bitung', 'Tomohon', 'Kotamobagu'],
  ST: ['Palu'],
  SN: ['Makassar', 'Parepare', 'Palopo'],
  SG: ['Kendari', 'Bau-Bau'],
  GO: ['Gorontalo'],
  SR: ['Mamuju'],
  MA: ['Ambon', 'Tual'],
  MU: ['Ternate', 'Tidore Kepulauan'],
  PA: ['Jayapura'],
  PB: ['Sorong', 'Manokwari'],
  PD: ['Sorong'],
  PS: ['Merauke'],
  PT: ['Nabire'],
  PP: ['Wamena']
}
